/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Config.Config;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Muh
 */
public class Dashboard extends javax.swing.JFrame {
    //Init var
    public Config config;

    /**
     * When menu logout clicked or not login yet, make some menu cannot 
     * be access until they login again.
    */
    private void setMenuLogout() {
        menuDaftar.setEnabled(true);
        menuLogin.setEnabled(true);
        menuExit.setEnabled(true);
        menuTransaksi.setEnabled(false);
        menuBarang.setEnabled(false);
        menuLogout.setEnabled(false);
        menuPengguna.setEnabled(false);
    }
    
    /**
     * When menu user success login, make some menu can be access 
     * until they logout or program closed.
    */
    private void setMenuLogin() {
        menuDaftar.setEnabled(false);
        menuLogin.setEnabled(false);
        menuExit.setEnabled(true);
        menuTransaksi.setEnabled(true);
        menuBarang.setEnabled(true);
        menuLogout.setEnabled(true);
        menuPengguna.setEnabled(true);
    }
    
    /**
     * This method is used for check user already registered or have a valid
     * account in our database.
     * @return true if username and password valid.
     */
    public boolean cekLogin(){
        String namaPengguna = "";
        try{
            String sql="SELECT * FROM pengguna WHERE username='"
                    +textUsername.getText()+
                    "' and password ='"+textPassword.getText()+"'";
            ResultSet rs = config.getData(sql);
            while (rs.next()){
                namaPengguna = rs.getString(1);
            }
            if(namaPengguna.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Login Gagal!");    
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Anda Berhasil Login!"
                +"\nSelamat Datang " + namaPengguna);
                setMenuLogin();
                dialogLogin.setVisible(false);
                return true;
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ada Kesalahan: " + e);
         }
        return false;
    }
     
    public Dashboard() {
        initComponents();
        setMenuLogout();
        config = new Config();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogLogin = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        textPassword = new javax.swing.JPasswordField();
        dialogDaftar = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDaftarUsername = new javax.swing.JTextField();
        txtDaftarNama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDaftarPassword = new javax.swing.JPasswordField();
        btnDaftar = new javax.swing.JButton();
        labelLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAuth = new javax.swing.JMenu();
        menuDaftar = new javax.swing.JMenuItem();
        menuLogin = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        menuMenu = new javax.swing.JMenu();
        menuPengguna = new javax.swing.JMenuItem();
        menuBarang = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();

        dialogLogin.setTitle("Login | Flash Laundry");
        dialogLogin.setMinimumSize(new java.awt.Dimension(400, 462));
        dialogLogin.setResizable(false);
        dialogLogin.setSize(new java.awt.Dimension(400, 462));

        jLabel3.setFont(new java.awt.Font("Lato", 1, 30)); // NOI18N
        jLabel3.setText("Login");

        jLabel4.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel5.setText("Password");

        textUsername.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        textUsername.setText("admin");

        btnBatal.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        textPassword.setText("admin");

        javax.swing.GroupLayout dialogLoginLayout = new javax.swing.GroupLayout(dialogLogin.getContentPane());
        dialogLogin.getContentPane().setLayout(dialogLoginLayout);
        dialogLoginLayout.setHorizontalGroup(
            dialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLoginLayout.createSequentialGroup()
                .addGroup(dialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogLoginLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel3))
                    .addGroup(dialogLoginLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4))
                    .addGroup(dialogLoginLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogLoginLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel5))
                    .addGroup(dialogLoginLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(dialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(dialogLoginLayout.createSequentialGroup()
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        dialogLoginLayout.setVerticalGroup(
            dialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLoginLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(dialogLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogDaftar.setMinimumSize(new java.awt.Dimension(400, 450));
        dialogDaftar.setPreferredSize(new java.awt.Dimension(400, 450));

        jLabel6.setFont(new java.awt.Font("Lato", 1, 30)); // NOI18N
        jLabel6.setText("DAFTAR");

        jLabel7.setText("Username");

        txtDaftarUsername.setToolTipText("adwa");

        txtDaftarNama.setToolTipText("adwa");

        jLabel8.setText("Nama");

        jLabel9.setText("Password");

        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        labelLogin.setForeground(new java.awt.Color(0, 51, 255));
        labelLogin.setText("Sudah punya akun? Klik disini");
        labelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dialogDaftarLayout = new javax.swing.GroupLayout(dialogDaftar.getContentPane());
        dialogDaftar.getContentPane().setLayout(dialogDaftarLayout);
        dialogDaftarLayout.setHorizontalGroup(
            dialogDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDaftarLayout.createSequentialGroup()
                .addGroup(dialogDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogDaftarLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(dialogDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(dialogDaftarLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDaftarUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogDaftarLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(dialogDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDaftarNama, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txtDaftarPassword)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(dialogDaftarLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogDaftarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(133, 133, 133))
            .addGroup(dialogDaftarLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(labelLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogDaftarLayout.setVerticalGroup(
            dialogDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDaftarLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addGroup(dialogDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDaftarUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDaftarNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDaftarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnDaftar)
                .addGap(44, 44, 44)
                .addComponent(labelLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consigndigue");
        setBackground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(556, 222));
        setResizable(false);
        setSize(new java.awt.Dimension(546, 252));

        jLabel1.setText("Selamat Datang di Consigndigue...");

        menuAuth.setText("Auth");

        menuDaftar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuDaftar.setText("Daftar");
        menuDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDaftarActionPerformed(evt);
            }
        });
        menuAuth.add(menuDaftar);

        menuLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        menuAuth.add(menuLogin);

        menuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuAuth.add(menuLogout);

        jMenuBar1.add(menuAuth);

        menuMenu.setText("Management");

        menuPengguna.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuPengguna.setText("Pengguna");
        menuPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenggunaActionPerformed(evt);
            }
        });
        menuMenu.add(menuPengguna);

        menuBarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        menuBarang.setText("Barang");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        menuMenu.add(menuBarang);

        menuTransaksi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuTransaksi.setText("Transaksi");
        menuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiActionPerformed(evt);
            }
        });
        menuMenu.add(menuTransaksi);

        jMenuBar1.add(menuMenu);

        menuExit.setText("Exit");
        menuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When menu login clicked do:
     * set text field null, then show dialog login.
    */
    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
//        textUsername.setText("");
//        textPassword.setText("");
        dialogLogin.setVisible(true);
        dialogLogin.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuLoginActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog (null, "Yakin ingin logout?");
        if(dialogResult == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Anda berhasil logout");
            setMenuLogout();
        }
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenggunaActionPerformed
        new ManagePengguna().show();
    }//GEN-LAST:event_menuPenggunaActionPerformed

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
        new ManageBarang().show();
    }//GEN-LAST:event_menuBarangActionPerformed

    private void menuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiActionPerformed
        new ManageTransaksi().show();
    }//GEN-LAST:event_menuTransaksiActionPerformed

    private void menuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuExitMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        boolean loginCheck = cekLogin();
        if(loginCheck == true) dialogLogin.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void menuDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDaftarActionPerformed
        dialogDaftar.setVisible(true);
        dialogDaftar.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuDaftarActionPerformed

    private void labelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginMouseClicked
        dialogDaftar.setVisible(false);
        dialogLogin.setVisible(true);
        dialogLogin.setLocationRelativeTo(null);
    }//GEN-LAST:event_labelLoginMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dialogDaftar.setVisible(false);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        String username = txtDaftarUsername.getText();
        String nama_pengguna = txtDaftarNama.getText();
        String password = txtDaftarPassword.getText();
        if ((username.isEmpty()) | (nama_pengguna.isEmpty()) | (password.isEmpty())){
            JOptionPane.showMessageDialog(null, "data tidak boleh kosong, " +
                "silahkan dilengkapi");
            textUsername.requestFocus();
        }else {
            try {
                String sql = "INSERT INTO pengguna (username, nama_pengguna, password) "
                        + "VALUES ("
                        + "'" + username + "',"
                        + "'" + nama_pengguna + "',"
                        + "'" + password + "'"
                + ")";
                config.query(sql);
                JOptionPane.showMessageDialog(null, "Berhasil membuat akun");
                dialogDaftar.setVisible(false);
            }catch (Exception ex) {
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnDaftarActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JDialog dialogDaftar;
    private javax.swing.JDialog dialogLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JMenu menuAuth;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenuItem menuDaftar;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenuItem menuPengguna;
    private javax.swing.JMenuItem menuTransaksi;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsername;
    private javax.swing.JTextField txtDaftarNama;
    private javax.swing.JPasswordField txtDaftarPassword;
    private javax.swing.JTextField txtDaftarUsername;
    // End of variables declaration//GEN-END:variables
}
